name: ${name}
main: tc.oc.rocket.RocketPlugin
version: ${project.version}
author: MonsieurApple

commands:
  rocket:
    description: Manage rocket settings
    usage: /<command> [toggle|reset]

permissions:
  rocket.admin:
    description: Allows usage of /rocket
    default: op
  rocket.rocket:
    description: Allows rocketing of other players via left click
    default: true
  rocket.exempt:
    description: Exempts users from being rocketed
    default: false
